#%RAML 1.0 Trait
headers:
  client_id:
    type: string
    description: client id to authenticate system api
    required: true
  client_secert:
    type: string
    description: client id to authenticate system api
    required: true