#%RAML 1.0 Trait
  usage: use this trait to ensure costumer sending this id for end to end tracking of transaction
  headers:
    x-transaction-id:
      type: string
      required: false
      description: this id maintained over api
