#%RAML 1.0 Trait
usage: mule have its own transaction-id and consumer can correlate their own correlation-id to mule transaction-id.
headers:
    x-correlation-id:
      type: string
      required: false




